# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://marchforsciencegeneva.org
title: March for Science - Geneva
email: info@marchforsciencegeneva@gmail.com
author: MFS Geneva
description: > # "Write an awesome description for your new site here.
  Science is for everyone.
  Facts are real.
  Celebrate empiricism, April 22nd, 2017.
  The time is now.
copyright: 'Copyright &copy; 2017 MfS - Geneva. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    icon: envelope
    url: mailto:contact@marchforsciencegeneva.org
  - title: twitter
    url: https://twitter.com/ScienceMarchGVA
  - title: facebook
    url: https://www.facebook.com/marchforsciencegeneva/
  - title: github
    url: https://github.com/marchforsciencegeneva/marchforsciencegeneva.github.io
